### ISSUE TITLE
::selection selektorundan istifadə edə bilərsiniz

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [elvinyeka/Portfolio-WebSite#1]
[🔗](https://developer.mozilla.org/en-US/docs/Web/CSS/::selection)

```css
::selection {
    background-color: #000;
    color: #fff;
}
```
Saytınızda qəşəng göründü.
